### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by singhprincejeet**
Added code coverage

### CODE REVIEW

**Comment by silverAndroid** [comment]
@singhprincejeet can you update the branch so Kyle's changes don't show up

**Comment by koosoku** [comment]
@singhprincejeet yes please! you can do this by merging with master

**Comment by koosoku** [comment]
also, the git history is like weird right now, it duplicated one of the commits contents, but not the hash, the easiest solution, since this is a one commit change might be just to start a new branch off master and start from there.

**Comment by singhprincejeet** [comment]
Will do it

**Pull request closed without merging**
